# Generated by Django 3.1.7 on 2021-03-30 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Diary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='lesson',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='mark',
            name='mark',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='Lesson',
        ),
    ]
