# Generated by Django 3.1.7 on 2021-03-27 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_auto_20210327_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='writetask',
            name='test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tests.test'),
        ),
    ]
