# Generated by Django 3.1.7 on 2021-03-28 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0005_answersheet_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='writetask',
            name='practise',
        ),
    ]
