# Generated by Django 3.1.7 on 2021-03-30 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0006_remove_writetask_practise'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListenText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theory', models.TextField()),
                ('content', models.TextField()),
                ('test', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tests.test')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
