# Generated by Django 3.1.7 on 2021-03-30 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0007_listentext'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ListenText',
            new_name='ReadAndSayText',
        ),
    ]
