# Generated by Django 3.1.7 on 2021-03-30 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0009_auto_20210331_0025'),
    ]

    operations = [
        migrations.AddField(
            model_name='readandsaytext',
            name='number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='writetask',
            name='number',
            field=models.IntegerField(default=1),
        ),
    ]
