# Generated by Django 3.1.7 on 2021-03-31 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0010_auto_20210331_0051'),
    ]

    operations = [
        migrations.CreateModel(
            name='A',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b', models.FileField(upload_to='fuck/')),
            ],
        ),
    ]
