# Generated by Django 3.1.7 on 2021-04-01 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0011_a'),
    ]

    operations = [
        migrations.RenameField(
            model_name='readandsaytext',
            old_name='theory',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='writetask',
            old_name='theory',
            new_name='title',
        ),
    ]
