# Generated by Django 3.1.7 on 2021-04-01 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0012_auto_20210401_2010'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioDialog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('number', models.IntegerField(default=1)),
                ('content', models.FileField(upload_to='')),
                ('test', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tests.test')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
