# Generated by Django 3.1.7 on 2021-04-01 21:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0014_auto_20210402_0059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiodialog',
            name='id',
        ),
        migrations.RemoveField(
            model_name='readandsaytext',
            name='id',
        ),
        migrations.RemoveField(
            model_name='writetask',
            name='id',
        ),
        migrations.AlterField(
            model_name='audiodialog',
            name='custom_id',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='readandsaytext',
            name='custom_id',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='writetask',
            name='custom_id',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
