# Generated by Django 3.1.7 on 2021-04-01 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0015_auto_20210402_0059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audiodialog',
            old_name='custom_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='readandsaytext',
            old_name='custom_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='writetask',
            old_name='custom_id',
            new_name='id',
        ),
    ]
