# Generated by Django 3.1.7 on 2021-04-03 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0016_auto_20210402_0100'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioDialogAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.FileField(upload_to='audios')),
                ('answerSheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.answersheet')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.audiodialog')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReadAndSayAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.FileField(upload_to='audios')),
                ('answerSheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.answersheet')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.readandsaytext')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='LongWriteAnswer',
        ),
    ]
