# Generated by Django 3.1.7 on 2021-04-17 21:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0017_auto_20210404_0240'),
    ]

    operations = [
        migrations.DeleteModel(
            name='A',
        ),
        migrations.AddField(
            model_name='audiodialoganswer',
            name='temp_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='readandsayanswer',
            name='temp_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
