# Generated by Django 3.1.7 on 2021-04-17 21:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0018_auto_20210418_0028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiodialoganswer',
            name='id',
        ),
        migrations.RemoveField(
            model_name='readandsayanswer',
            name='id',
        ),
        migrations.AlterField(
            model_name='audiodialoganswer',
            name='temp_id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='readandsayanswer',
            name='temp_id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
