# Generated by Django 3.1.7 on 2021-04-17 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0019_auto_20210418_0028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audiodialoganswer',
            old_name='temp_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='readandsayanswer',
            old_name='temp_id',
            new_name='id',
        ),
    ]
