# Generated by Django 3.1.7 on 2021-04-26 15:24

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0020_auto_20210418_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiodialog',
            name='content',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='readandsaytext',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.CreateModel(
            name='ThemeSelectionAndSay',
            fields=[
                ('title', models.TextField()),
                ('number', models.IntegerField(default=1)),
                ('id', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('test', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tests.test')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
