# Generated by Django 3.1.7 on 2021-04-26 21:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0021_auto_20210426_1824'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeSelectionAndSayAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('content', models.FileField(upload_to='audios')),
                ('theme_selected', models.TextField()),
                ('answerSheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.answersheet')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.themeselectionandsay')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
